// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0--rc1
// source: Proto/MatandoPiso.proto

package Proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MercenarioMensaje struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peticion int32 `protobuf:"varint,1,opt,name=peticion,proto3" json:"peticion,omitempty"`
	Decision int32 `protobuf:"varint,2,opt,name=decision,proto3" json:"decision,omitempty"`
}

func (x *MercenarioMensaje) Reset() {
	*x = MercenarioMensaje{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_MatandoPiso_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MercenarioMensaje) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MercenarioMensaje) ProtoMessage() {}

func (x *MercenarioMensaje) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_MatandoPiso_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MercenarioMensaje.ProtoReflect.Descriptor instead.
func (*MercenarioMensaje) Descriptor() ([]byte, []int) {
	return file_Proto_MatandoPiso_proto_rawDescGZIP(), []int{0}
}

func (x *MercenarioMensaje) GetPeticion() int32 {
	if x != nil {
		return x.Peticion
	}
	return 0
}

func (x *MercenarioMensaje) GetDecision() int32 {
	if x != nil {
		return x.Decision
	}
	return 0
}

type DirectorMensaje struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inicio int32 `protobuf:"varint,1,opt,name=inicio,proto3" json:"inicio,omitempty"`
	Estado int32 `protobuf:"varint,2,opt,name=estado,proto3" json:"estado,omitempty"`
	Fase   int32 `protobuf:"varint,3,opt,name=fase,proto3" json:"fase,omitempty"`
}

func (x *DirectorMensaje) Reset() {
	*x = DirectorMensaje{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_MatandoPiso_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectorMensaje) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectorMensaje) ProtoMessage() {}

func (x *DirectorMensaje) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_MatandoPiso_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectorMensaje.ProtoReflect.Descriptor instead.
func (*DirectorMensaje) Descriptor() ([]byte, []int) {
	return file_Proto_MatandoPiso_proto_rawDescGZIP(), []int{1}
}

func (x *DirectorMensaje) GetInicio() int32 {
	if x != nil {
		return x.Inicio
	}
	return 0
}

func (x *DirectorMensaje) GetEstado() int32 {
	if x != nil {
		return x.Estado
	}
	return 0
}

func (x *DirectorMensaje) GetFase() int32 {
	if x != nil {
		return x.Fase
	}
	return 0
}

var File_Proto_MatandoPiso_proto protoreflect.FileDescriptor

var file_Proto_MatandoPiso_proto_rawDesc = []byte{
	0x0a, 0x17, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4d, 0x61, 0x74, 0x61, 0x6e, 0x64, 0x6f, 0x50,
	0x69, 0x73, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4b, 0x0a, 0x11, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x4d, 0x65,
	0x6e, 0x73, 0x61, 0x6a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x74, 0x69, 0x63, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x65, 0x74, 0x69, 0x63, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x55, 0x0a,
	0x0f, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x69, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x66, 0x61, 0x73, 0x65, 0x32, 0x50, 0x0a, 0x07, 0x4d, 0x65, 0x72, 0x63, 0x44, 0x69, 0x72, 0x12,
	0x45, 0x0a, 0x0f, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x18, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x61, 0x72, 0x69, 0x6f, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x1a, 0x16, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x6e,
	0x73, 0x61, 0x6a, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Proto_MatandoPiso_proto_rawDescOnce sync.Once
	file_Proto_MatandoPiso_proto_rawDescData = file_Proto_MatandoPiso_proto_rawDesc
)

func file_Proto_MatandoPiso_proto_rawDescGZIP() []byte {
	file_Proto_MatandoPiso_proto_rawDescOnce.Do(func() {
		file_Proto_MatandoPiso_proto_rawDescData = protoimpl.X.CompressGZIP(file_Proto_MatandoPiso_proto_rawDescData)
	})
	return file_Proto_MatandoPiso_proto_rawDescData
}

var file_Proto_MatandoPiso_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Proto_MatandoPiso_proto_goTypes = []interface{}{
	(*MercenarioMensaje)(nil), // 0: Proto.MercenarioMensaje
	(*DirectorMensaje)(nil),   // 1: Proto.DirectorMensaje
}
var file_Proto_MatandoPiso_proto_depIdxs = []int32{
	0, // 0: Proto.MercDir.MensajeDirector:input_type -> Proto.MercenarioMensaje
	1, // 1: Proto.MercDir.MensajeDirector:output_type -> Proto.DirectorMensaje
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Proto_MatandoPiso_proto_init() }
func file_Proto_MatandoPiso_proto_init() {
	if File_Proto_MatandoPiso_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Proto_MatandoPiso_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MercenarioMensaje); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_MatandoPiso_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectorMensaje); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Proto_MatandoPiso_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Proto_MatandoPiso_proto_goTypes,
		DependencyIndexes: file_Proto_MatandoPiso_proto_depIdxs,
		MessageInfos:      file_Proto_MatandoPiso_proto_msgTypes,
	}.Build()
	File_Proto_MatandoPiso_proto = out.File
	file_Proto_MatandoPiso_proto_rawDesc = nil
	file_Proto_MatandoPiso_proto_goTypes = nil
	file_Proto_MatandoPiso_proto_depIdxs = nil
}
